language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - yarn docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  repo: axe-api/axe-api.github.io
  target_branch: master
  name: Travis Bot
  on:
    branch: master
